tiles.setCurrentTilemap(tilemap`level1`)
let Jedi = sprites.create(img`
    ........................
    .......fff..............
    ....fffff2f.............
    ..ffeeeee22ff...........
    .ffeeeeee222ff..........
    .feeeefffeeeef..........
    .fffffeee2222ef.........
    fffe222fffffe2f.........
    fffffffffeeefff.....cc..
    fefe44ebbf44eef...ccdc..
    .fee4d4bbfddef..ccddcc..
    ..feee4dddddfeecdddc....
    ...f2222222eeddcdcc.....
    ...f444445e44ddccc......
    ...ffffffffeeee.........
    ...fff...ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
Jedi.setPosition(15, 15)
controller.moveSprite(Jedi)
scene.cameraFollowSprite(Jedi)
game.onUpdateInterval(1000, function () {
    console.log("" + Jedi.x + Jedi.y)
})
